[[redirects]]
  from = "/api/*"
  to = "https://explorer-foodapp.onrender.com/:splat"
  status = 200
  force = true
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"